[package]
name = "lsts"
version = "0.0.25"
authors = ["Andrew <andrew@subarctic.org>"]
license = "MIT"
description = "Large Scale Type Systems"
edition = "2018"
readme = "README.md"
repository = "https://github.com/andrew-johnson-4/LSTS"
documentation = "https://docs.rs/lsts/"
keywords = ["type","logic","automated","theorem","proof"]

[dependencies]
pest = { version = "2.1.3" }
pest_derive = { version = "2.1.0" }
