[package]
name = "lsts"
version = "0.5.18"
authors = ["Andrew <andrew@subarctic.org>"]
license = "MIT"
description = "Large Scale Type Systems"
edition = "2018"
readme = "README.md"
repository = "https://github.com/andrew-johnson-4/LSTS"
documentation = "https://docs.rs/lsts/"
keywords = ["type","logic","automated","theorem","proof"]

[dependencies]
regex = { version = "1" }

[profile.release]
opt-level = 3

[profile.test]
opt-level = 3

[[bin]]
name = "lsts"
path = "src/main.rs"
